### ISSUE TITLE
cleaning and verifying records [PR possible]

### ISSUE THREAD

**Issue by vltr** [jyn-n/dnsblock#3]
Hello! I was using your repository as a solution for extra-privacy (with dnsmasq), but for some time now I'm unable to use it basically because there's a lot of domains that contains `^M` in their lines, repeating themselves but also breaking lines, resulting in (truncated example):

```
...
address=/02k.pl/0.0.0.0
address=/02k.pl
/0.0.0.0
address=/02m.pl/0.0.0.0
address=/02m.pl
/0.0.0.0
address=/0365.bid/0.0.0.0
...
```

Also, there are a lot of "invalid addresses" that results in abnormal lines, line (truncated example again):

```
...
address=/127.0.0.1 abz.com/0.0.0.0
address=/127.0.0.1 accounts.pkr.com.invalid/0.0.0.0
address=/127.0.0.1 a.collective-media.net/0.0.0.0
address=/127.0.0.1 a.consumer.net/0.0.0.0
address=/127.0.0.1 a-counter.kiev.ua/0.0.0.0
...
```

So, a bit of cleaning and validating are required to properly generate your files ... I'm willing to work on it and submit a PR if you're too busy or simply would accept my help :smiley:

Just let me know that you think.

BTW, thanks for your work and effort on that!! :clap:

**Comment by jyn-n** [comment]
Hey Richard, thanks for pointing that out. Help is always welcome. There was a problem with different encodings from different sources so i applied a quick and dirty fix for now which should be working at least for some time.

I was planning on adding some more sources and at the same time implement a cleaner approach for merging different lists when i get down to it. One of these days...

**Comment by vltr** [comment]
@jyn-n no problem! Thanks for the quick return. If I tumble across a solution for this, I'll let you know :wink:
