### ISSUE TITLE
make install not work on Ubuntu  18

### ISSUE THREAD

**Issue by fenggui321** [jyn-n/dnsblock#6]
sh update_dl_file.sh steven_black.dl
update_dl_file.sh: 3: update_dl_file.sh: declare: not found
update_dl_file.sh: 4: update_dl_file.sh: Syntax error: "(" unexpected
makefile:28: recipe for target 'steven_black.dl' failed
make: *** [steven_black.dl] Error 2

**Comment by jyn-n** [comment]
What shell are you using? More specifically, what is your output of `/bin/bash --version`
There are some shells that do not suport the arrays that seem to cause the problem for you.

**Comment by fenggui321** [comment]
/bin/bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by jyn-n** [comment]
Should be fixed now

**Comment by fenggui321** [comment]
that work for me now!   thanks  for your help.
